LOADING AND MERGIND THE 9 FILES

In [33]:
import pandas as pd

In [34]:
good_faith = pd.read_csv("Good Faithh.csv")
good_faith

,Account Name,2019,2020,2021,2022,2023
0,Total Assets,0,0,"66,045,912.00","74,532,015.25","78,895,301.12"
1,Total Deposit liabilities,0,0,"47,580,831.00","51,641,674.00","56,120,443.00"
2,Total Equity,0,0,"15,603,894.00","19,350,690.00","19,842,551.00"
3,Total Liabilities,0,0,"50,442,019.00","55,181,326.00","59,052,750.12"
4,Cash & Cash Equivalent,0,0,"19,799,397.00","20,884,959.00","16,902,420.89"
5,Financial Investments,0,0,"25,330.00","24,550.00","24,550.00"
6,Gross Loan Portfolio,0,0,"47,572,950.00","52,516,192.00","60,320,115.00"
7,Net Loan Portfolio,0,0,"37,252,147.00","44,088,836.25","45,612,990.00"
8,Current Year's Surplus,0,0,0,0,"2,855,717.00"
9,Share Capital,0,0,"10,271,434.00","10,720,832.00","11,245,600.00"
10,Statutory Reserve,0,0,0,"4,030,156.00","4,210,340.00"

In [35]:
good_way = pd.read_csv("Goodwayy Sacco.csv")
good_way

,Account Name,2019,2020,2021,2022,2023*
0,Total Assets,"45,621,444","49,793,828","56,660,235","60,579,585","47,562,451"
1,Total Deposit liabilities,"19,185,646","23,669,977","30,511,071","28,679,000","33,372,882"
2,Total Equity,"21,784,320","23,142,108","23,368,609","23,404,025","13,961,213"
3,Total Liabilities,"23,837,124","26,651,721","34,068,710","36,872,613","33,601,238"
4,Cash & Cash Equivalent,"5,913,431","8,460,800","7,528,330","3,906,758","4,254,981"
5,Financial Investments,"914,790","1,121,325","1,811,583","1,825,751",0
6,Gross Loan Portfolio,"35,170,961","35,483,959","38,088,372","44,270,076","39,675,444"
7,Net Loan Portfolio,"34,556,455","34,818,647","37,148,812","43,353,686","39,250,917"
8,Current Year's Surplus,"2,763,822","1,306,803","853,669","1,171,271","-1,170,167"
9,Share Capital,"11,986,229","11,986,229","11,986,229","13,324,579","13,328,478"
10,Statutory Reserve,"2,552,633","2,934,091","3,104,825","3,404,384","478,205"

In [36]:
hazina = pd.read_csv("Hazina Accounts.csv")
hazina

,Account Name,2019,2020,2021,2022,2023
0,Total Assets,"8,432,323,283","9,144,307,882","10,470,223,736","11,887,605,966","13,380,422,968"
1,Total Deposit Liabilities,"6,290,093,029","6,864,888,284","7,935,970,950","9,183,165,337","10,421,787,092"
2,Total Equity,"1,847,566,350","2,050,421,795","2,342,752,943","2,492,028,881","2,758,541,745"
3,Total Liabilities,"6,584,756,933","7,093,886,087","8,127,470,793","9,395,577,085","10,621,881,223"
4,Cash & Cash Equivalent,"448,510,967","640,432,593","1,223,803,506","1,466,423,767","1,518,225,934"
5,Financial Investments,"205,372,217","129,569,217","254,495,353","277,159,335","323,178,853"
6,Gross Loan Portfolio,"7,267,006,204","7,725,650,490","8,368,098,735","9,471,061,048","10,879,738,103"
7,Net Loan Portfolio,"7,126,202,308","7,575,178,217","8,205,091,894","9,286,837,211","10,668,024,575"
8,Current Year's Surplus,"805,102,590","838,620,016","986,508,610","1,113,874,103","1,215,622,410"
9,Share Capital,"506,009,469","572,267,522","682,755,758","800,227,998","913,546,477"
10,Statutory Reserve,"329,481,214","363,225,214","402,945,558","447,495,522","496,120,418"

In [37]:
home_business = pd.read_csv("Home business accounts approval .csv")
home_business

,Account Name,2019,2020,2021,2022,2023
0,Total Assets,"8,432,323,283","9,144,307,882","10,470,223,736","11,887,605,966","13,380,422,968"
1,Total Deposit Liabilities,"6,290,093,029","6,864,888,284","7,935,970,950","9,183,165,337","10,421,787,092"
2,Total Equity,"1,847,566,350","2,050,421,795","2,342,752,943","2,492,028,881","2,758,541,745"
3,Total Liabilities,"6,584,756,933","7,093,886,087","8,127,470,793","9,395,577,085","10,621,881,223"
4,Cash & Cash Equivalent,"448,510,967","640,432,593","1,223,803,506","1,466,423,767","1,518,225,934"
5,Financial Investments,"205,372,217","129,569,217","254,495,353","277,159,335","323,178,853"
6,Gross Loan Portfolio,"7,267,006,204","7,725,650,490","8,368,098,735","9,471,061,048","10,879,738,103"
7,Net Loan Portfolio,"7,126,202,308","7,575,178,217","8,205,091,894","9,286,837,211","10,668,024,575"
8,Current Year's Surplus,"805,102,590","838,620,016","986,508,610","1,113,874,103","1,215,622,410"
9,Share Capital,"506,009,469","572,267,522","682,755,758","800,227,998","913,546,477"
10,Statutory Reserve,"329,481,214","363,225,214","402,945,558","447,495,522","496,120,418"

In [38]:
ig = pd.read_csv("Home business accounts approval .csv")
ig

,Account Name,2019,2020,2021,2022,2023
0,Total Assets,"8,432,323,283","9,144,307,882","10,470,223,736","11,887,605,966","13,380,422,968"
1,Total Deposit Liabilities,"6,290,093,029","6,864,888,284","7,935,970,950","9,183,165,337","10,421,787,092"
2,Total Equity,"1,847,566,350","2,050,421,795","2,342,752,943","2,492,028,881","2,758,541,745"
3,Total Liabilities,"6,584,756,933","7,093,886,087","8,127,470,793","9,395,577,085","10,621,881,223"
4,Cash & Cash Equivalent,"448,510,967","640,432,593","1,223,803,506","1,466,423,767","1,518,225,934"
5,Financial Investments,"205,372,217","129,569,217","254,495,353","277,159,335","323,178,853"
6,Gross Loan Portfolio,"7,267,006,204","7,725,650,490","8,368,098,735","9,471,061,048","10,879,738,103"
7,Net Loan Portfolio,"7,126,202,308","7,575,178,217","8,205,091,894","9,286,837,211","10,668,024,575"
8,Current Year's Surplus,"805,102,590","838,620,016","986,508,610","1,113,874,103","1,215,622,410"
9,Share Capital,"506,009,469","572,267,522","682,755,758","800,227,998","913,546,477"
10,Statutory Reserve,"329,481,214","363,225,214","402,945,558","447,495,522","496,120,418"

In [39]:
imarika = pd.read_csv("Imarika Sacco.csv")
imarika

,Account Name,2019,2020,2021,2022,2023
0,Total Assets,"9,152,783,165","9,737,422,176","10,131,847,994","10,876,432,155","11,452,180,000"
1,Total Deposit liabilities,"6,523,104,882","7,102,455,102","7,650,895,221","8,241,550,112","8,785,420,000"
2,Total Equity,"1,489,522,114","1,852,595,720","2,287,004,974","2,805,068,100","2,950,115,000"
3,Total Liabilities,"7,663,261,051","7,884,826,456","7,844,843,020","8,071,364,055","8,502,065,000"
4,Cash & Cash Equivalent,"19,363,224","893,579,487","753,154,463","903,255,082","1,017,417,813"
5,Financial Investments,"412,550,000","455,120,000","495,220,000","545,880,000","560,110,000"
6,Gross Loan Portfolio,"7,416,940,385","8,138,168,521","8,754,220,110","9,742,715,677","10,210,440,000"
7,Net Loan Portfolio,"7,034,090,878","7,712,450,110","8,311,245,660","9,259,367,894","9,705,369,818"
8,Current Year's Surplus,"357,685,310","398,929,049","446,035,664","486,112,000","252,410,000"
9,Share Capital,"488,412,000","554,120,000","632,550,000","715,700,250","740,115,000"
10,Statutory Reserve,"312,450,000","385,120,000","452,110,000","512,330,000",NaN

In [40]:
jamii = pd.read_csv("Jamii.csv")
jamii

,Account Name,2019,2020,2021,2022,2023
0,Total Assets,0,"4,662,154,303","5,091,966,231","5,443,177,821","5,455,210,400"
1,Total Deposit Liabilities,0,"3,117,070,083","3,748,605,103","3,658,074,923","3,682,144,210"
2,Total Equity,0,"1,173,151,332","1,445,452,703","1,293,503,287","1,321,440,550"
3,Total Liabilities,0,"3,489,002,971","3,646,513,528","4,149,674,534","4,133,769,850"
4,Cash & Cash Equivalent,0,"371,352,866","462,253,410","962,830,488","855,320,110"
5,Financial Investments,0,"355,548,222","447,346,472","122,325,438","125,440,000"
6,Gross Loan Portfolio,0,"3,556,155,701","4,318,047,024","4,960,112,058","4,982,550,600"
7,Net Loan Portfolio,0,"3,248,349,650","3,063,015,547","3,705,080,581","3,721,440,000"
8,Current Year's Surplus,0,"462,063,290","117,708,139","341,691,000","85,241,105"
9,Share Capital,0,"446,959,264","1,091,106,575","535,449,040","545,220,300"
10,Statutory Reserve,0,"181,817,320","181,817,320","281,223,963","281,223,963"

In [41]:
kenya_achievas = pd.read_csv("Kenya Achievas.csv")
kenya_achievas

,Account Name,2019,2020,2021,2022,2023
0,Total Assets,"412,300,818.84","392,978,893.46","390,333,250.97","453,443,496.04","421,806,711.82"
1,Total Deposit liabilities,"194,093,679.00","161,826,693.19","159,987,193.76","277,015,576.80","183,577,223.74"
2,Total Equity,"105,761,017.00","171,427,377.93","184,897,762.71","164,804,805.68","203,156,911.68"
3,Total Liabilities,"306,539,801.84","221,551,515.53","205,435,488.26","288,638,690.36","218,649,800.14"
4,Cash & Cash Equivalent,"70,985,223.00","38,341,912.77","28,993,165.31","52,603,285.81","33,993,917.77"
5,Financial Investments,"44,390,000.00","83,871,738.59","58,635,118.87","47,484,117.43","39,903,530.86"
6,Gross Loan Portfolio,"181,659,592.98","146,599,270.00","174,987,267.88","362,796,441.40","230,772,846.46"
7,Net Loan Portfolio,"174,526,543.00","119,582,723.61","148,161,380.41","323,727,897.14","203,760,744.43"
8,Current Year's Surplus,"487,234.00","5,367,586.27","11,401,373.05",0,"13,119,960.50"
9,Share Capital,"37,090,876.00","118,844,476.36","125,122,050.09","67,256,355.38","139,571,307.88"
10,Statutory Reserve,"10,576,101.00","8,663,255.00","8,922,657.00","16,572,514.97","9,788,098.00"

In [42]:
kenya_bankers = pd.read_csv("Kenya Bankers.csv")
kenya_bankers

,Account Name,2019,2020,2021,2022,2023
0,Total Assets,"8,021,456,200","9,103,337,522","9,103,337,522","9,976,326,084","10,543,210,000"
1,Total Deposit liabilities,"6,120,550,000","6,662,966,562","6,845,210,400","7,100,000,000","7,500,000,000"
2,Total Equity,"950,440,000","1,402,167,718","1,199,743,992","1,300,000,000","1,500,000,000"
3,Total Liabilities,"7,071,016,200","7,701,169,804","7,903,593,530","8,200,000,000","8,700,000,000"
4,Cash & Cash Equivalent,"150,200,000","195,018,007","136,268,767","140,000,000","160,000,000"
5,Financial Investments,"70,000,000","76,980,777","81,097,852","85,000,000","90,000,000"
6,Gross Loan Portfolio,"6,200,500,000","6,902,718,973","7,026,325,423","7,500,000,000","8,100,000,000"
7,Net Loan Portfolio,"5,800,400,000","6,454,710,541","6,747,324,365","7,200,000,000","7,800,000,000"
8,Current Year's Surplus,"65,000,000","88,400,500","94,210,300","110,000,000","130,000,000"
9,Share Capital,"420,500,000","468,993,626","472,219,391","480,000,000","500,000,000"
10,Statutory Reserve,"145,000,000","160,648,412","173,217,839","185,000,000","200,000,000"

In [43]:
combined_df = pd.concat([good_faith, good_way, hazina, home_business, ig, imarika, jamii, kenya_achievas, kenya_bankers], axis=0)
combined_df

,Account Name,2019,2020,2021,2022,2023,2023*
0,Total Assets,0,0,"66,045,912.00","74,532,015.25","78,895,301.12",NaN
1,Total Deposit liabilities,0,0,"47,580,831.00","51,641,674.00","56,120,443.00",NaN
2,Total Equity,0,0,"15,603,894.00","19,350,690.00","19,842,551.00",NaN
3,Total Liabilities,0,0,"50,442,019.00","55,181,326.00","59,052,750.12",NaN
4,Cash & Cash Equivalent,0,0,"19,799,397.00","20,884,959.00","16,902,420.89",NaN
...,...,...,...,...,...,...,...
6,Gross Loan Portfolio,"6,200,500,000","6,902,718,973","7,026,325,423","7,500,000,000","8,100,000,000",NaN
7,Net Loan Portfolio,"5,800,400,000","6,454,710,541","6,747,324,365","7,200,000,000","7,800,000,000",NaN
8,Current Year's Surplus,"65,000,000","88,400,500","94,210,300","110,000,000","130,000,000",NaN
9,Share Capital,"420,500,000","468,993,626","472,219,391","480,000,000","500,000,000",NaN
10,Statutory Reserve,"145,000,000","160,648,412","173,217,839","185,000,000","200,000,000",NaN

In [44]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 99 entries, 0 to 10
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Account Name  99 non-null     object
 1   2019          99 non-null     object
 2   2020          99 non-null     object
 3   2021          99 non-null     object
 4   2022          99 non-null     object
 5   2023          87 non-null     object
 6   2023*         11 non-null     object
dtypes: object(7)
memory usage: 6.2+ KB