## Step 1: Loading the Dataset

In this step, we load the SACCO audited accounts dataset into our environment.

The dataset is stored in the `data/` folder within our project directory.

Loading the data allows us to begin exploring its structure and preparing it for analysis.

We start with a single Excel file before scaling to multiple datasets.

In [1]:
import pandas as pd

df = pd.read_excel("data/Acumen Audited Accounts 2023.xlsx")

## Step 2: Previewing the Dataset

After loading the dataset, we inspect the first few rows to understand its structure.

This helps us:
- Get a quick view of the data
- Understand how columns are organized
- Identify any obvious issues (missing values, formatting)

This is the first step in understanding the dataset before deeper analysis.

In [2]:
df.head()

,Unnamed: 0,ACUMEN SACCO SOCIETY,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,NaN,STATEMENT OF FINANCIAL POSITION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,FINANCIAL YEAR 2021,Aud-2019,Aud-2020,Jan,Feb,Mar,Apr,May,Jun,...,2022-08-01 00:00:00,2022-09-01 00:00:00,2022-10-01 00:00:00,2022-11-01 00:00:00,2022-12-01 00:00:00,audited 2022,NaN,NaN,NaN,NaN
2,1,Cash & Cash Equivalent,10834463,60942575,1.75885e+07,1.71399e+07,1.66703e+07,2.03301e+07,2.12939e+07,2.43101e+07,...,52281693,58048024,62794651,6.30557e+07,77262741,77254741,NaN,NaN,NaN,NaN
3,1.1,Cash in hand(both local and foreign notes and ...,250946,1162644,0,0,0,0,0,0,...,12187787,17550823,21997216,1.5032e+07,1229050,1.22905e+06,NaN,NaN,NaN,NaN
4,1.2,Cash at bank:(placement with financial institu...,10583517,59779931,1.75885e+07,1.71399e+07,1.66703e+07,2.03301e+07,2.12939e+07,2.43101e+07,...,40093906,40497201,40797435,4.80236e+07,76033691,7.60257e+07,NaN,NaN,NaN,NaN

## Step 3: Initial Data Issues

From the preview, the dataset is not in a clean tabular format.

Key issues observed:
- Column names are labeled as "Unnamed"
- The first few rows contain titles and metadata instead of actual data
- Data appears to start from a lower row

This is common in financial reports exported from Excel.

To proceed, we need to:
- Identify the correct header row
- Reload the dataset using the correct structure

In [3]:
df = pd.read_excel("data/Acumen Audited Accounts 2023.xlsx", skiprows=2)
df.head()

,Unnamed: 0,FINANCIAL YEAR 2021,Aud-2019,Aud-2020,Jan,Feb,Mar,Apr,May,Jun,...,2022-08-01 00:00:00,2022-09-01 00:00:00,2022-10-01 00:00:00,2022-11-01 00:00:00,2022-12-01 00:00:00,audited 2022,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,1,Cash & Cash Equivalent,10834463.0,60942575.0,17588524.65,17139917.86,16670330.97,20330140.74,21293871.83,24310141.01,...,52281693.0,58048024.0,62794651.0,63055663.28,77262741.0,77254741.00,NaN,NaN,NaN,NaN
1,1.1,Cash in hand(both local and foreign notes and ...,250946.0,1162644.0,0.00,0.00,0.00,0.00,0.00,0.00,...,12187787.0,17550823.0,21997216.0,15032040.68,1229050.0,1229050.75,NaN,NaN,NaN,NaN
2,1.2,Cash at bank:(placement with financial institu...,10583517.0,59779931.0,17588524.65,17139917.86,16670330.97,20330140.74,21293871.83,24310141.01,...,40093906.0,40497201.0,40797435.0,48023622.60,76033691.0,76025690.25,NaN,NaN,NaN,NaN
3,2,Prepayments & Sundry Receivables,8620453.0,11664214.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.00,0.0,11282181.00,NaN,-8289401.16,NaN,NaN
4,3,Financial Investments,115855.0,115855.0,41747825.78,42026698.00,42341640.92,35634084.84,35905690.98,36173046.56,...,115855.0,115855.0,115855.0,115855.00,115855.0,115855.00,NaN,NaN,NaN,NaN

## Step 4: Understanding Data Structure

After cleaning the header rows, the dataset now shows financial line items across multiple time periods.

Key observations:
- Each row represents a financial category (e.g. Cash, Investments)
- Columns represent different time periods (years and months)
- The dataset is in a wide format

To prepare for analysis, we will:
- Rename key columns
- Reshape the dataset into a structured format suitable for analysis

In [15]:
df = df.rename(columns={
    'Unnamed: 0': 'Account_ID',
    'FINANCIAL YEAR 2021': 'Account_Name'
})

df.head()

,Account_ID,Account_Name,Aud-2019,Aud-2020,Jan,Feb,Mar,Apr,May,Jun,...,NaN,NaN,NaN,NaN,NaN,audited 2022,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,1,Cash & Cash Equivalent,10834463.0,60942575.0,17588524.65,17139917.86,16670330.97,20330140.74,21293871.83,24310141.01,...,52281693.0,58048024.0,62794651.0,63055663.28,77262741.0,77254741.00,NaN,NaN,NaN,NaN
1,1.1,Cash in hand(both local and foreign notes and ...,250946.0,1162644.0,0.00,0.00,0.00,0.00,0.00,0.00,...,12187787.0,17550823.0,21997216.0,15032040.68,1229050.0,1229050.75,NaN,NaN,NaN,NaN
2,1.2,Cash at bank:(placement with financial institu...,10583517.0,59779931.0,17588524.65,17139917.86,16670330.97,20330140.74,21293871.83,24310141.01,...,40093906.0,40497201.0,40797435.0,48023622.60,76033691.0,76025690.25,NaN,NaN,NaN,NaN
3,2,Prepayments & Sundry Receivables,8620453.0,11664214.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.00,0.0,11282181.00,NaN,-8289401.16,NaN,NaN
4,3,Financial Investments,115855.0,115855.0,41747825.78,42026698.00,42341640.92,35634084.84,35905690.98,36173046.56,...,115855.0,115855.0,115855.0,115855.00,115855.0,115855.00,NaN,NaN,NaN,NaN

In [ ]:
## Step 5: Cleaning Column Names

Some column names contained hidden spaces, which prevented proper renaming.

We cleaned the column names by removing extra spaces and then renamed key columns:
- Account_ID
- Account_Name

This ensures consistency and avoids errors in later steps.

In [12]:
#renaming again
df = df.rename(columns={
    'Unnamed: 0': 'Account_ID',
    'FINANCIAL YEAR  2021': 'Account_Name'
})

In [13]:
#checking again
df.head()

,Account_ID,Account_Name,Aud-2019,Aud-2020,Jan,Feb,Mar,Apr,May,Jun,...,NaN,NaN,NaN,NaN,NaN,audited 2022,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,1,Cash & Cash Equivalent,10834463.0,60942575.0,17588524.65,17139917.86,16670330.97,20330140.74,21293871.83,24310141.01,...,52281693.0,58048024.0,62794651.0,63055663.28,77262741.0,77254741.00,NaN,NaN,NaN,NaN
1,1.1,Cash in hand(both local and foreign notes and ...,250946.0,1162644.0,0.00,0.00,0.00,0.00,0.00,0.00,...,12187787.0,17550823.0,21997216.0,15032040.68,1229050.0,1229050.75,NaN,NaN,NaN,NaN
2,1.2,Cash at bank:(placement with financial institu...,10583517.0,59779931.0,17588524.65,17139917.86,16670330.97,20330140.74,21293871.83,24310141.01,...,40093906.0,40497201.0,40797435.0,48023622.60,76033691.0,76025690.25,NaN,NaN,NaN,NaN
3,2,Prepayments & Sundry Receivables,8620453.0,11664214.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.00,0.0,11282181.00,NaN,-8289401.16,NaN,NaN
4,3,Financial Investments,115855.0,115855.0,41747825.78,42026698.00,42341640.92,35634084.84,35905690.98,36173046.56,...,115855.0,115855.0,115855.0,115855.00,115855.0,115855.00,NaN,NaN,NaN,NaN

## Step 6: Removing Irrelevant Columns

The dataset contains several empty or irrelevant columns labeled as "Unnamed".

These columns do not provide useful information for analysis and may introduce errors.

We remove these columns to simplify the dataset and focus only on meaningful data.

In [17]:
df.columns.str.contains('Unnamed')

Index([False, False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,   nan,   nan,   nan,
         nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan,   nan, False,
        True,  True,  True,  True],
      dtype='object')

In [18]:
df = df.loc[:, ~df.columns.astype(str).str.contains('Unnamed')]

df.head()

,Account_ID,Account_Name,Aud-2019,Aud-2020,Jan,Feb,Mar,Apr,May,Jun,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,audited 2022
0,1,Cash & Cash Equivalent,10834463.0,60942575.0,17588524.65,17139917.86,16670330.97,20330140.74,21293871.83,24310141.01,...,44314258.0,47378805.93,49968245.55,52249064.44,52281693.0,58048024.0,62794651.0,63055663.28,77262741.0,77254741.00
1,1.1,Cash in hand(both local and foreign notes and ...,250946.0,1162644.0,0.00,0.00,0.00,0.00,0.00,0.00,...,5403363.0,8177749.93,10487055.59,8472651.02,12187787.0,17550823.0,21997216.0,15032040.68,1229050.0,1229050.75
2,1.2,Cash at bank:(placement with financial institu...,10583517.0,59779931.0,17588524.65,17139917.86,16670330.97,20330140.74,21293871.83,24310141.01,...,38910895.0,39201056.00,39481189.96,43776413.42,40093906.0,40497201.0,40797435.0,48023622.60,76033691.0,76025690.25
3,2,Prepayments & Sundry Receivables,8620453.0,11664214.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,0.0,11282181.00
4,3,Financial Investments,115855.0,115855.0,41747825.78,42026698.00,42341640.92,35634084.84,35905690.98,36173046.56,...,115855.0,115855.00,115855.00,115855.00,115855.0,115855.0,115855.0,115855.00,115855.0,115855.00

## Step 7: Reshaping the Dataset (Wide to Long Format)

The dataset is currently in a wide format where each time period (months and years) is represented as a separate column.

This structure is not suitable for analysis or modeling.

To make the data usable, we convert it into a long format where:
- Each row represents a single observation
- Time periods are stored in one column
- Values are stored in another column

This transformation is essential for time series analysis and predictive modeling.

In [19]:
df_long = df.melt(
    id_vars=['Account_ID', 'Account_Name'],
    var_name='Date',
    value_name='Value'
)

df_long.head()

,Account_ID,Account_Name,Date,Value
0,1,Cash & Cash Equivalent,Aud-2019,10834463.0
1,1.1,Cash in hand(both local and foreign notes and ...,Aud-2019,250946.0
2,1.2,Cash at bank:(placement with financial institu...,Aud-2019,10583517.0
3,2,Prepayments & Sundry Receivables,Aud-2019,8620453.0
4,3,Financial Investments,Aud-2019,115855.0

## Step 8: Structured Dataset Achieved

The dataset has now been transformed into a long format.

Each row represents:
- A financial category (Account_Name)
- A specific time period (Date)
- A corresponding value (Value)

This structure allows us to:
- Analyze trends over time
- Compare financial categories
- Prepare the data for feature selection and modeling

In [20]:
df_long['Date'].unique()

array(['Aud-2019', 'Aud-2020', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
       'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Aud-21', nan,
       'audited 2022'], dtype=object)

## Step 9: Cleaning the Date Column

The Date column contains inconsistent formats, including:
- Year-based values (e.g. Aud-2019, audited 2022)
- Month names (e.g. Jan, Feb)
- Missing values

To make the dataset usable, we standardize the Date column into a consistent format.

This step is essential for time-based analysis and modeling.

In [21]:
import numpy as np

def clean_date(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip().lower()
    
    if "2019" in x:
        return "2019"
    elif "2020" in x:
        return "2020"
    elif "21" in x:
        return "2021"
    elif "2022" in x:
        return "2022"
    else:
        return x.capitalize()  # Jan, Feb, etc.

df_long['Clean_Date'] = df_long['Date'].apply(clean_date)

df_long[['Date', 'Clean_Date']].drop_duplicates()

              Date Clean_Date
0         Aud-2019       2019
49        Aud-2020       2020
98             Jan        Jan
147            Feb        Feb
196            Mar        Mar
245            Apr        Apr
294            May        May
343            Jun        Jun
392            Jul        Jul
441            Aug        Aug
490            Sep        Sep
539            Oct        Oct
588            Nov        Nov
637            Dec        Dec
686         Aud-21       2021
735            NaN        NaN
1323  audited 2022       2022

## Step 10: Removing Invalid Dates

Some rows contain missing date values.

These rows do not contribute to time-based analysis and may introduce errors.

We remove them to ensure the dataset is clean and consistent.

In [22]:
df_long = df_long.dropna(subset=['Clean_Date'])

df_long['Clean_Date'].unique()

array(['2019', '2020', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul',
       'Aug', 'Sep', 'Oct', 'Nov', 'Dec', '2021', '2022'], dtype=object)

## Step 11: Creating Features from Financial Categories

Currently, financial categories (Account_Name) exist as rows.

To prepare for analysis and modeling, we convert these into columns.

This transformation creates a structured dataset where:
- Each row represents a time period
- Each column represents a financial feature

In [23]:
df_pivot = df_long.pivot_table(
    index='Clean_Date',
    columns='Account_Name',
    values='Value',
    aggfunc='sum'
)

df_pivot.head()

Account_Name,Accounts Payable & Other Liabilities,Accounts Receivables,Adjustment to Equity,Allowance for Loan Loss,Balances with other SACCO Societies,Capital Grants,Cash & Cash Equivalent,Cash at bank:(placement with financial institutions),Cash in hand(both local and foreign notes and coins),Current Year's Surplus,...,Share Capital (Members share capital per Bylaws),"Short Term Deposits (e.g Fixed deposits, special savings)",Statutory Reserve,Tax Payable,Tax Recoverable,Total Assets,Total Deposit liabilities,Total Equity,Total Liabilities,Total Liabilities and Equity
Clean_Date,,,,,,,,,,,,,,,,,,,,,
2019,14172704.00,0.0,0.0,1460356.00,0.0,0.0,10834463.00,10583517.00,250946.00,710651.00,...,17276340.00,552646.0,5780960.00,3610.0,0.0,2.693712e+08,2.216134e+08,33585269.00,2.357861e+08,2.693714e+08
2020,413121.00,0.0,0.0,21319244.00,0.0,0.0,60942575.00,59779931.00,1162644.00,17320.00,...,18970134.00,708204.0,5780960.03,14602.0,0.0,2.934117e+08,2.577053e+08,35288951.22,2.581184e+08,2.934073e+08
2021,19393076.00,0.0,0.0,11418650.00,0.0,0.0,56687339.00,55509402.00,1177937.00,15839579.00,...,20674211.00,968674.0,9745185.00,1046054.0,0.0,3.694371e+08,2.963373e+08,53706746.00,3.157304e+08,3.694371e+08
2022,19435937.00,0.0,0.0,15133841.28,0.0,0.0,77254741.00,76025690.25,1229050.75,3103704.00,...,29563201.00,0.0,10521111.00,967553.0,0.0,4.033872e+08,3.205462e+08,63405036.00,3.399821e+08,4.033872e+08
Apr,563322.84,0.0,0.0,17374702.38,0.0,0.0,20330140.74,20330140.74,0.00,5756177.71,...,19441092.47,0.0,5785290.03,13002.0,0.0,3.179216e+08,2.694771e+08,47881097.21,2.700405e+08,3.179216e+08

## Step 12: Final Structured Dataset

The dataset has been successfully transformed into a structured format suitable for analysis.

Key characteristics:
- Each row represents a time period
- Each column represents a financial variable (feature)
- Values represent financial amounts

This structure allows for:
- Time series analysis
- Feature selection
- Predictive modeling

This marks the transition from data preparation to analytical modeling.

## Step 13: Filtering Annual Data

The dataset contains both monthly and yearly data.

To simplify analysis and ensure consistency, we focus on annual data only.

This reduces noise and allows for clearer trend analysis and modeling.

In [24]:
df_pivot = df_pivot.loc[['2019', '2020', '2021', '2022']]

df_pivot

Account_Name,Accounts Payable & Other Liabilities,Accounts Receivables,Adjustment to Equity,Allowance for Loan Loss,Balances with other SACCO Societies,Capital Grants,Cash & Cash Equivalent,Cash at bank:(placement with financial institutions),Cash in hand(both local and foreign notes and coins),Current Year's Surplus,...,Share Capital (Members share capital per Bylaws),"Short Term Deposits (e.g Fixed deposits, special savings)",Statutory Reserve,Tax Payable,Tax Recoverable,Total Assets,Total Deposit liabilities,Total Equity,Total Liabilities,Total Liabilities and Equity
Clean_Date,,,,,,,,,,,,,,,,,,,,,
2019,14172704.0,0.0,0.0,1460356.00,0.0,0.0,10834463.0,10583517.00,250946.00,710651.0,...,17276340.0,552646.0,5780960.00,3610.0,0.0,2.693712e+08,2.216134e+08,33585269.00,2.357861e+08,269371400.0
2020,413121.0,0.0,0.0,21319244.00,0.0,0.0,60942575.0,59779931.00,1162644.00,17320.0,...,18970134.0,708204.0,5780960.03,14602.0,0.0,2.934117e+08,2.577053e+08,35288951.22,2.581184e+08,293407347.8
2021,19393076.0,0.0,0.0,11418650.00,0.0,0.0,56687339.0,55509402.00,1177937.00,15839579.0,...,20674211.0,968674.0,9745185.00,1046054.0,0.0,3.694371e+08,2.963373e+08,53706746.00,3.157304e+08,369437114.0
2022,19435937.0,0.0,0.0,15133841.28,0.0,0.0,77254741.0,76025690.25,1229050.75,3103704.0,...,29563201.0,0.0,10521111.00,967553.0,0.0,4.033872e+08,3.205462e+08,63405036.00,3.399821e+08,403387181.0

## Step 14: Feature Selection 

Feature selection is based on actual available financial variables in the dataset.

We select key variables that represent:
- Financial strength
- Lending activity
- Liquidity
- Capital structure

These features are important for predicting SACCO performance.

In [27]:
#Step 15-Creating model dataset
features = [
    'Total Assets',
    'Total Deposit liabilities',
    'Total Equity',
    'Total Liabilities',
    'Cash & Cash Equivalent',
    'Financial Investments',
    'Gross Loan Portfolio',
    'Net Loan Portfolio',
    'Non withdrawable deposits (BOSA member deposits)',
    'Share Capital (Members share capital per Bylaws)',
    'Statutory Reserve'
]

target = "Current Year's Surplus"

In [26]:
list(df_pivot.columns)

['Accounts Payable & Other Liabilities',
 'Accounts Receivables',
 'Adjustment to Equity',
 'Allowance for Loan Loss',
 'Balances with other SACCO Societies',
 'Capital Grants',
 'Cash & Cash Equivalent',
 'Cash at bank:(placement with financial institutions)',
 'Cash in hand(both local and foreign notes and coins)',
 "Current Year's Surplus",
 'Deferred Tax Assets',
 'Deferred Tax Liability',
 'Dividends Payable',
 'External Borrowings',
 'Financial Investments',
 'Government Securities - Treasury Bills/bonds,  ',
 'Gross Loan Portfolio',
 'Intangible Assets',
 'Investment Properties',
 'Investments in companies - shares/stocks ',
 'Net Loan Portfolio',
 'Non withdrawable deposits (BOSA member deposits)',
 'Other Assets',
 'Other Equity Accounts',
 'Other Liabilities',
 'Other Reserves (provide notes on these reserves)',
 'Other Securities - Commercial papers/Bonds',
 'Prepaid Lease rentals',
 'Prepayments & Sundry Receivables',
 "Prior Years' Retained Earnings",
 'Property & Equipment',
 'Property & Equipment & Other assets',
 'Proposed Dividends',
 'Retained Earnings',
 'Retirement Benefit Assets',
 'Retirement Benefits Liability',
 'Revaluation Reserves (Not part of core capital)',
 'Savings Deposits - Withdrawable deposits - FOSA)',
 'Share Capital (Members share capital per Bylaws)',
 'Short Term Deposits (e.g Fixed deposits, special savings)',
 'Statutory Reserve',
 'Tax Payable',
 'Tax Recoverable',
 'Total Assets',
 'Total Deposit liabilities',
 'Total Equity',
 'Total Liabilities',
 'Total Liabilities and  Equity']

In [28]:
#Build Model Dataset.
df_model = df_pivot[features + [target]]

df_model

Account_Name,Total Assets,Total Deposit liabilities,Total Equity,Total Liabilities,Cash & Cash Equivalent,Financial Investments,Gross Loan Portfolio,Net Loan Portfolio,Non withdrawable deposits (BOSA member deposits),Share Capital (Members share capital per Bylaws),Statutory Reserve,Current Year's Surplus
Clean_Date,,,,,,,,,,,,
2019,2.693712e+08,2.216134e+08,33585269.00,2.357861e+08,10834463.0,115855.0,2.475976e+08,2.461372e+08,220316533.0,17276340.0,5780960.00,710651.0
2020,2.934117e+08,2.577053e+08,35288951.22,2.581184e+08,60942575.0,115855.0,2.382020e+08,2.168827e+08,254720687.0,18970134.0,5780960.03,17320.0
2021,3.694371e+08,2.963373e+08,53706746.00,3.157304e+08,56687339.0,115855.0,3.122795e+08,3.008609e+08,287470465.0,20674211.0,9745185.00,15839579.0
2022,4.033872e+08,3.205462e+08,63405036.00,3.399821e+08,77254741.0,115855.0,3.224364e+08,3.073025e+08,312478374.0,29563201.0,10521111.00,3103704.0

## Step 15: Final Modeling Dataset

The dataset has been refined to include only relevant financial features and the target variable.

Features selected represent:
- Financial size (Total Assets)
- Funding structure (Deposits, Equity)
- Lending activity (Loan Portfolio)
- Liquidity (Cash)
- Capital strength (Reserves, Share Capital)

Target variable:
- Current Year's Surplus (used as a measure of SACCO performance)

This dataset is now ready for predictive modeling.